# Pytorch_Basics

### pytorch tensors

An short introduction about PyTorch and about the chosen functions. 
- torch.as_tensor()
- torch.reshape()
- torch.squeeze()
- torch.t()
- torch.cat()

In [125]:
# Import torch and other required modules
import torch
import numpy as np

## 1. torch.tensor() vs torch.as_tensor()

Zero memory-copy (very efficient)

In [126]:
d = np.array([[1,2], [3,4]])
 
# factory f'n
    
t1 = torch.tensor(d)  
t2 = torch.as_tensor(d)
t3 = torch.from_numpy(d)

t4 = torch.Tensor(d) # constructor

print(t1)
print(t4)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


Here,`torch.tensor()` and `torch.Tensor()` always creates copy of the data.<br>
whereas, `torch.as_tensor()` and `torch.from_numpy()` shares the data d <br>
        i.e. they don't create new m/o instead creates a pointer pointin to data.

In [127]:
d[0][0] = 9

print(t1)
print(t4)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1., 2.],
        [3., 4.]])
tensor([[9, 2],
        [3, 4]], dtype=torch.int32)
tensor([[9, 2],
        [3, 4]], dtype=torch.int32)


If we change the original data d , change is also reflected in t2 and t3.

In [128]:
print(t4.dtype)
t4

torch.float32


tensor([[1., 2.],
        [3., 4.]])

In [129]:
torch.get_default_dtype()

torch.float32

Notice here, torch.Tensor is a constructor and <br>data passed was int32 but t4 dtype is float32.<br>

torch.Tensor assigns data to default datatype i.e float32

In [130]:
dl = [[1,2],[3,4]]  #list

tl1 = torch.from_numpy(dl)

TypeError: expected np.ndarray (got list)


`torch.from_numpy()` function only accepts numpy.ndarrays, <br>while the `torch.as_tensor()` function accepts other variety too such as list.<br>


In [131]:
tl1 = torch.as_tensor(dl)
tl1

tensor([[1, 2],
        [3, 4]])

## 2. reshape()

Changes shape of tensor to the specified shape but with the same data and number of elements as input.

In [132]:
 t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
])

print(f"Rank: {len(t.shape)}")    
print(f"no. of elems: {t.numel()}")
t.shape

Rank: 2
no. of elems: 12


torch.Size([3, 4])

shape of tensor and size is same thing.

In [133]:
t.reshape([2,6])

tensor([[1, 1, 1, 1, 2, 2],
        [2, 2, 3, 3, 3, 3]])

In [134]:
t.reshape([4,3])

tensor([[1, 1, 1],
        [1, 2, 2],
        [2, 2, 3],
        [3, 3, 3]])

In [135]:
t.reshape(1,-1)  # same as t.reshape([1,12]) , can use if 12 is unknown 

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [136]:
t.reshape(2,2,3) # can also increase the rank of tensor

tensor([[[1, 1, 1],
         [1, 2, 2]],

        [[2, 2, 3],
         [3, 3, 3]]])

While reshaping the tensor, data and no. of elements are same, just size is modified.

In [137]:
t.reshape([3,6])

RuntimeError: shape '[3, 6]' is invalid for input of size 12

6x3 = 18 , therefore the tensor for size 12 can't be transformed.

## 3. squeeze()

Squeezing a tensor removes the dimensions or axes that have a length of one.

In [138]:
t = t.reshape(1,-1)
print(t.shape)
t

torch.Size([1, 12])


tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

this reshaping gives flattened tensor but rank is 2 and size(1,12).

In [139]:
tr = t.squeeze()
print(t.shape)
tr

torch.Size([1, 12])


tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

with `squeeze()` rank/dimension is decreased.

In [140]:
print(tr.unsqueeze(dim=1))
print(tr.unsqueeze(dim=0))

tensor([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]])
tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])


`unsqueeze()` can be used to do revese i.e increasing the rank.

In [141]:
tr = t.reshape([6,2])
print(tr.squeeze())
tr.unsqueeze(dim=0)

tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]])


tensor([[[1, 1],
         [1, 1],
         [2, 2],
         [2, 2],
         [3, 3],
         [3, 3]]])

Here there in no dimensions of length 1 so tensor size remains the same.<br>
but, can be unsqueezed

## 4. torch.t(x)

Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.

In [151]:
x = torch.randn(4,3)
x

tensor([[ 0.6578,  0.3057,  0.8777],
        [-0.3586,  0.4123, -1.0336],
        [-0.7004, -1.7553,  1.5306],
        [-0.6648,  0.8039, -0.4013]])

`torch.randn()` Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 

In [152]:
torch.t(x)

tensor([[ 0.6578, -0.3586, -0.7004, -0.6648],
        [ 0.3057,  0.4123, -1.7553,  0.8039],
        [ 0.8777, -1.0336,  1.5306, -0.4013]])

returns the transpose of the tensor

In [144]:
y = torch.rand(2,3,4)
print(y)
torch.t(y)

tensor([[[0.8573, 0.2915, 0.8963, 0.1056],
         [0.3040, 0.0852, 0.9746, 0.5156],
         [0.0915, 0.5199, 0.6390, 0.9429]],

        [[0.0931, 0.5485, 0.7476, 0.8499],
         [0.2552, 0.5190, 0.1909, 0.0848],
         [0.2000, 0.6600, 0.6962, 0.5286]]])


RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

f'n breaks for tensor with dimensions > 2 

## 5. torch.cat()

Concatenates the given sequence of seq tensors in the given dimension

In [145]:
x = torch.randint(5,(2,2,3))
print(x)

y = torch.randint(8,(2,2,3))
print()
y

tensor([[[0, 4, 2],
         [2, 0, 0]],

        [[0, 2, 2],
         [2, 4, 0]]])



tensor([[[7, 2, 3],
         [1, 1, 5]],

        [[4, 3, 4],
         [1, 6, 2]]])

Created 3 dimenssional tensor

In [146]:
torch.cat((x,y), 2)

tensor([[[0, 4, 2, 7, 2, 3],
         [2, 0, 0, 1, 1, 5]],

        [[0, 2, 2, 4, 3, 4],
         [2, 4, 0, 1, 6, 2]]])

In [147]:
torch.cat((x,y,x), 1)

tensor([[[0, 4, 2],
         [2, 0, 0],
         [7, 2, 3],
         [1, 1, 5],
         [0, 4, 2],
         [2, 0, 0]],

        [[0, 2, 2],
         [2, 4, 0],
         [4, 3, 4],
         [1, 6, 2],
         [0, 2, 2],
         [2, 4, 0]]])

In [148]:
torch.cat((x,y), 0)

tensor([[[0, 4, 2],
         [2, 0, 0]],

        [[0, 2, 2],
         [2, 4, 0]],

        [[7, 2, 3],
         [1, 1, 5]],

        [[4, 3, 4],
         [1, 6, 2]]])

When we concatenate tensors, we increase the number of elements contained within the resulting tensor.

In [149]:
z = torch.randint(5,(2,3))
print("x Rank:" , len(x.shape))
print("z Rank:",len(z.shape))
torch.cat((x,z), 0)

x Rank: 3
z Rank: 2


RuntimeError: Tensors must have same number of dimensions: got 3 and 2

tensors having differnt dimensions can't be concatenated.

concatenation is simillar like addition

## Conclusion

This notebook discusses some of the basic tensor functions which are usefull in modifications and further computations.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* This Article : https://deeplizard.com/learn/video/AglLTlms7HU